# Generated by Django 2.0.6 on 2018-06-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Imagem:'),
        ),
    ]
