# Generated by Django 2.0.6 on 2018-06-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180611_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itens',
        ),
    ]
