# Generated by Django 2.0.6 on 2018-11-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0004_auto_20181116_1504'),
        ('armario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmarioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Armário',
                'verbose_name_plural': 'Armários',
            },
        ),
        migrations.AlterModelOptions(
            name='armario',
            options={},
        ),
        migrations.AddField(
            model_name='armarioitem',
            name='armario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armario.Armario'),
        ),
        migrations.AddField(
            model_name='armarioitem',
            name='itens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.Itens'),
        ),
    ]
