# Generated by Django 2.0.6 on 2018-06-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armario',
            options={'ordering': ['name'], 'verbose_name': 'Armário', 'verbose_name_plural': 'Armários'},
        ),
        migrations.AddField(
            model_name='armario',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
