# Generated by Django 2.0.6 on 2018-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0002_auto_20180614_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='armario',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='armario',
            name='created_at',
            field=models.DateField(verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='armario',
            name='updated_at',
            field=models.DateField(verbose_name='Atualizado em'),
        ),
    ]
