# Generated by Django 2.0.6 on 2018-11-17 18:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0002_auto_20181116_1557'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='armario',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='armario',
            old_name='user_id',
            new_name='user',
        ),
    ]
