# Generated by Django 2.0.6 on 2018-06-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0003_auto_20180615_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armario',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='armario',
            name='updated_at',
        ),
    ]
