# Generated by Django 2.0.6 on 2018-11-29 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0003_auto_20181117_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armario',
            options={'ordering': ['name'], 'verbose_name': 'Armário', 'verbose_name_plural': 'Armários'},
        ),
        migrations.AlterModelOptions(
            name='armarioitem',
            options={},
        ),
        migrations.AlterField(
            model_name='armario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
