# Generated by Django 2.0.6 on 2018-11-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0004_auto_20180615_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='armario',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='armario',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='armario',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='armario',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
