# Generated by Django 2.0.6 on 2018-11-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categoria', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_item', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome:')),
                ('slug', models.SlugField(verbose_name='Atalho:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem:')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.Categoria')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.Cor')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['name'],
            },
        ),
    ]
