# Generated by Django 2.0.6 on 2018-11-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='itens_headshots/'),
        ),
    ]
