# Generated by Django 2.0.6 on 2018-11-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_itens_headshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='headshot',
        ),
        migrations.AlterField(
            model_name='itens',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='itens_imagens', verbose_name='Imagem:'),
        ),
    ]
