# Generated by Django 2.0.6 on 2018-06-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_auto_20180612_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itens',
            options={'ordering': ['name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
