# Generated by Django 2.0.6 on 2018-06-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0004_auto_20180612_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem:'),
        ),
    ]
