# Generated by Django 2.0.6 on 2018-06-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0005_auto_20180614_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='categoria',
            field=models.CharField(max_length=20, null=True, verbose_name='Categoria'),
        ),
    ]
